eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: mall-search
  data:
    elasticsearch:
      clusterNodes: 127.0.0.1:9300

server:
  port: 8084

