eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: mall-zuul

server:
  port: 8081

ignore:
  urls: /login
  authUrls: /login,/manager/managerauthoritys,/authority/test,/upload

jwt:
  jwtSecretKey: bGVjc2hvcF9qd3Rfc2VjcmV0X2tleQ==
